"use client";

import { RotateCcw, Search } from "lucide-react";
import { useId, useState, type MouseEvent, type ReactNode } from "react";
import { cn } from "../shared/cn";
import { Alert, AlertDescription, AlertTitle, Button, Card, Input, Skeleton, Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "../ui";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, Label, Pagination, PaginationContent, PaginationEllipsis, PaginationFirst, PaginationItem, PaginationLast, PaginationLink, PaginationNext, PaginationPrevious, Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "../ui/client";
import type { ButtonProps } from "../ui";

export interface PatternMessages {
  cancel: string; confirm: string; confirming: string; reset: string; keyword: string; keywordPlaceholder: string; pageSize: string; itemSuffix: string; emptyTitle: string; emptyDescription: string; errorTitle: string; loading: string; pagination: string; first: string; previous: string; next: string; last: string; morePages: string; total: (count: number) => string; page: (current: number, total: number) => string; pageLabel: (page: number) => string;
}
export const enUSPatternMessages: PatternMessages = { cancel: "Cancel", confirm: "Confirm", confirming: "Working...", reset: "Reset", keyword: "Keyword", keywordPlaceholder: "Filter by keyword", pageSize: "Page size", itemSuffix: "", emptyTitle: "No records", emptyDescription: "Adjust the filters and try again.", errorTitle: "Request failed", loading: "Loading...", pagination: "Pagination", first: "First", previous: "Previous", next: "Next", last: "Last", morePages: "More pages", total: (count) => `${count} records`, page: (current, total) => `Page ${current} of ${Math.max(total, 1)}`, pageLabel: (page) => `Page ${page}` };
export const zhCNPatternMessages: PatternMessages = { cancel: "取消", confirm: "确认", confirming: "处理中...", reset: "重置", keyword: "关键词", keywordPlaceholder: "输入关键词筛选", pageSize: "每页数量", itemSuffix: " 条", emptyTitle: "暂无记录", emptyDescription: "调整筛选条件后重试。", errorTitle: "请求失败", loading: "正在加载...", pagination: "分页", first: "首页", previous: "上一页", next: "下一页", last: "末页", morePages: "更多页面", total: (count) => `共 ${count} 条记录`, page: (current, total) => `第 ${current} / ${Math.max(total, 1)} 页`, pageLabel: (page) => `第 ${page} 页` };

export interface PageMeta { page: number; size: number; total: number; pages: number; has_next: boolean; has_prev: boolean; }
export interface ConfirmationDialogProps { title?: string; description?: string; open: boolean; onOpenChange: (open: boolean) => void; onConfirm: () => void | Promise<void>; onConfirmError?: (error: unknown) => void; cancelLabel?: string; confirmLabel?: string; confirmVariant?: Extract<NonNullable<ButtonProps["variant"]>, "default" | "destructive">; pending?: boolean; messages?: PatternMessages; }
export function ConfirmationDialog({ title = "Confirm action", description = "Confirm that you want to continue.", open, onOpenChange, onConfirm, onConfirmError, cancelLabel, confirmLabel, confirmVariant = "destructive", pending = false, messages = enUSPatternMessages }: ConfirmationDialogProps) { const [confirming, setConfirming] = useState(false); const busy = pending || confirming; async function confirm(event: MouseEvent<HTMLButtonElement>) { event.preventDefault(); if (busy) return; setConfirming(true); try { await onConfirm(); onOpenChange(false); } catch (error) { onConfirmError?.(error); } finally { setConfirming(false); } } return <AlertDialog open={open} onOpenChange={(next) => { if (!busy) onOpenChange(next); }}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{title}</AlertDialogTitle><AlertDialogDescription>{description}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={busy}>{cancelLabel ?? messages.cancel}</AlertDialogCancel><AlertDialogAction variant={confirmVariant} disabled={busy} onClick={confirm}>{busy ? messages.confirming : confirmLabel ?? messages.confirm}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>; }

export interface PaginationControlsProps { page: PageMeta; onPageChange: (page: number) => void; className?: string; messages?: PatternMessages; }
export function PaginationControls({ page, onPageChange, className, messages = enUSPatternMessages }: PaginationControlsProps) { const total = Number.isSafeInteger(page.pages) ? Math.max(page.pages, 0) : 0; const current = total === 0 ? 1 : Math.min(Math.max(Number.isSafeInteger(page.page) ? page.page : 1, 1), total); const first = total === 0 || current === 1; const last = total === 0 || current === total; return <Pagination aria-label={messages.pagination} className={className}><PaginationContent className="justify-end"><PaginationItem><PaginationFirst aria-label={messages.first} disabled={first} onClick={() => onPageChange(1)}>{messages.first}</PaginationFirst></PaginationItem><PaginationItem><PaginationPrevious aria-label={messages.previous} disabled={first} onClick={() => onPageChange(current - 1)}>{messages.previous}</PaginationPrevious></PaginationItem>{tokens(total, current).map((token, index) => <PaginationItem key={`${token}-${index}`}>{token === "ellipsis" ? <PaginationEllipsis label={messages.morePages} /> : <PaginationLink aria-label={messages.pageLabel(token)} isActive={token === current} disabled={token === current} onClick={() => onPageChange(token)}>{token}</PaginationLink>}</PaginationItem>)}<PaginationItem><PaginationNext aria-label={messages.next} disabled={last} onClick={() => onPageChange(current + 1)}>{messages.next}</PaginationNext></PaginationItem><PaginationItem><PaginationLast aria-label={messages.last} disabled={last} onClick={() => onPageChange(total)}>{messages.last}</PaginationLast></PaginationItem></PaginationContent></Pagination>; }
function tokens(total: number, current: number): Array<number | "ellipsis"> { if (!total) return []; if (total <= 7) return Array.from({ length: total }, (_, i) => i + 1); if (current <= 3) return [1, 2, 3, 4, "ellipsis", total]; if (current >= total - 2) return [1, "ellipsis", total - 3, total - 2, total - 1, total]; return [1, "ellipsis", current - 1, current, current + 1, "ellipsis", total]; }

export interface DataTableColumn<T> { key: string; label: string; render: (row: T) => ReactNode; className?: string; }
export interface DataTableProps<T> { columns: Array<DataTableColumn<T>>; rows: T[]; rowKey: (row: T) => string; page: PageMeta; isLoading?: boolean; error?: string | null; emptyTitle?: string; emptyDescription?: string; onPageChange?: (page: number) => void; messages?: PatternMessages; }
export function DataTable<T>({ columns, rows, rowKey, page, isLoading = false, error, emptyTitle, emptyDescription, onPageChange, messages = enUSPatternMessages }: DataTableProps<T>) { const count = Math.max(columns.length, 1); return <Card className="overflow-hidden p-0 shadow-none sm:p-0"><div className="flex justify-between border-b px-4 py-3 text-[length:var(--text-body-sm)] text-[color:var(--muted-foreground)]"><span>{messages.total(page.total)}</span><span>{messages.page(page.page, page.pages)}</span></div><Table><TableHeader><TableRow>{columns.map((column) => <TableHead key={column.key} className={column.className}>{column.label}</TableHead>)}</TableRow></TableHeader><TableBody>{isLoading ? Array.from({ length: 5 }, (_, index) => <TableRow key={index}>{Array.from({ length: count }, (_, cell) => <TableCell key={cell}><Skeleton className="h-4 w-4/5" /></TableCell>)}</TableRow>) : error ? <TableRow><TableCell colSpan={count}><Alert variant="destructive"><AlertDescription>{error}</AlertDescription></Alert></TableCell></TableRow> : rows.length === 0 ? <TableRow><TableCell colSpan={count} className="py-12 text-center"><div role="status"><strong>{emptyTitle ?? messages.emptyTitle}</strong><p>{emptyDescription ?? messages.emptyDescription}</p></div></TableCell></TableRow> : rows.map((row) => <TableRow key={rowKey(row)}>{columns.map((column) => <TableCell key={column.key} className={column.className}>{column.render(row)}</TableCell>)}</TableRow>)}</TableBody></Table>{onPageChange ? <PaginationControls className="border-t px-4 py-3" page={page} onPageChange={onPageChange} messages={messages} /> : null}</Card>; }

export interface FilterBarProps { keyword: string; pageSize: number; onKeywordChange: (keyword: string) => void; onPageSizeChange: (size: number) => void; onReset: () => void; keywordLabel?: string; keywordPlaceholder?: string; pageSizes?: readonly number[]; children?: ReactNode; messages?: PatternMessages; }
export function FilterBar({ keyword, pageSize, onKeywordChange, onPageSizeChange, onReset, keywordLabel, keywordPlaceholder, pageSizes = [10, 20, 50, 100], children, messages = enUSPatternMessages }: FilterBarProps) { const id = useId(); return <Card className="grid grid-cols-1 items-end gap-3 p-4 shadow-none sm:flex sm:flex-wrap sm:p-4"><div className="grid min-w-0 w-full flex-1 gap-1.5 sm:min-w-[14rem]"><Label htmlFor={`${id}-keyword`}>{keywordLabel ?? messages.keyword}</Label><div className="relative"><Search aria-hidden="true" className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-[color:var(--muted-foreground)]" /><Input id={`${id}-keyword`} className="pl-9" value={keyword} onChange={(event) => onKeywordChange(event.target.value)} placeholder={keywordPlaceholder ?? messages.keywordPlaceholder} /></div></div>{children ? <div className="min-w-0 w-full sm:w-auto">{children}</div> : null}<div className="grid w-full justify-items-start gap-1.5 sm:w-auto"><Label htmlFor={`${id}-size`}>{messages.pageSize}</Label><Select value={String(pageSize)} onValueChange={(value) => onPageSizeChange(Number(value))}><SelectTrigger id={`${id}-size`} className="w-[6.5rem]"><SelectValue /></SelectTrigger><SelectContent>{pageSizes.map((size) => <SelectItem key={size} value={String(size)}>{size}{messages.itemSuffix}</SelectItem>)}</SelectContent></Select></div><Button type="button" variant="outline" className="w-full sm:w-auto" onClick={onReset}><RotateCcw aria-hidden="true" className="size-4" />{messages.reset}</Button></Card>; }

export interface ManagementDialogProps { open: boolean; onOpenChange: (open: boolean) => void; title: string; description: string; children: ReactNode; closeLabel?: string; }
export function ManagementDialog({ open, onOpenChange, title, description, children, closeLabel }: ManagementDialogProps) { return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent closeLabel={closeLabel}><DialogHeader><DialogTitle>{title}</DialogTitle><DialogDescription>{description}</DialogDescription></DialogHeader><div className="min-h-0 overflow-y-auto p-5">{children}</div></DialogContent></Dialog>; }
export interface ErrorStateProps { title?: string; message: string; messages?: PatternMessages; }
export function ErrorState({ title, message, messages = enUSPatternMessages }: ErrorStateProps) { return <Alert variant="destructive"><AlertTitle>{title ?? messages.errorTitle}</AlertTitle><AlertDescription>{message}</AlertDescription></Alert>; }
export interface LoadingStateProps { label?: string; messages?: PatternMessages; }
export function LoadingState({ label, messages = enUSPatternMessages }: LoadingStateProps) { return <Card className="flex items-center gap-3 px-4 py-3 shadow-none sm:px-4 sm:py-3"><Skeleton className="size-3" /><span>{label ?? messages.loading}</span></Card>; }
export { cn };
