// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: authentication.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bindBootstrapAdmin = `-- name: BindBootstrapAdmin :execrows
UPDATE authentication_settings SET bootstrap_admin_user_id=$1
WHERE singleton=TRUE AND (bootstrap_admin_user_id IS NULL OR bootstrap_admin_user_id=$1)
`

func (q *Queries) BindBootstrapAdmin(ctx context.Context, bootstrapAdminUserID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, bindBootstrapAdmin, bootstrapAdminUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const ensureSecuritySettings = `-- name: EnsureSecuritySettings :exec
INSERT INTO user_security_settings(user_id) VALUES ($1) ON CONFLICT DO NOTHING
`

func (q *Queries) EnsureSecuritySettings(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, ensureSecuritySettings, userID)
	return err
}

const getAuthenticationSettings = `-- name: GetAuthenticationSettings :one
SELECT singleton, password_login_enabled, registration_enabled, registration_email_verification_required, allowed_email_domains, bootstrap_admin_user_id, initialized_at FROM authentication_settings WHERE singleton = TRUE
`

func (q *Queries) GetAuthenticationSettings(ctx context.Context) (AuthenticationSetting, error) {
	row := q.db.QueryRow(ctx, getAuthenticationSettings)
	var i AuthenticationSetting
	err := row.Scan(
		&i.Singleton,
		&i.PasswordLoginEnabled,
		&i.RegistrationEnabled,
		&i.RegistrationEmailVerificationRequired,
		&i.AllowedEmailDomains,
		&i.BootstrapAdminUserID,
		&i.InitializedAt,
	)
	return i, err
}

const getSecuritySettings = `-- name: GetSecuritySettings :one
SELECT user_id, mode, totp_secret, pending_secret, pending_expires_at, last_totp_step, recovery_hashes, recovery_codes_expires_at, version FROM user_security_settings WHERE user_id=$1
`

func (q *Queries) GetSecuritySettings(ctx context.Context, userID pgtype.UUID) (UserSecuritySetting, error) {
	row := q.db.QueryRow(ctx, getSecuritySettings, userID)
	var i UserSecuritySetting
	err := row.Scan(
		&i.UserID,
		&i.Mode,
		&i.TotpSecret,
		&i.PendingSecret,
		&i.PendingExpiresAt,
		&i.LastTotpStep,
		&i.RecoveryHashes,
		&i.RecoveryCodesExpiresAt,
		&i.Version,
	)
	return i, err
}

const initializeAuthentication = `-- name: InitializeAuthentication :execrows
UPDATE authentication_settings SET initialized_at=COALESCE(initialized_at,NOW())
WHERE singleton=TRUE AND bootstrap_admin_user_id=$1
`

func (q *Queries) InitializeAuthentication(ctx context.Context, bootstrapAdminUserID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, initializeAuthentication, bootstrapAdminUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertAuthenticationConsumption = `-- name: InsertAuthenticationConsumption :exec
INSERT INTO authentication_consumptions(credential_id,expires_at) VALUES ($1,$2)
`

type InsertAuthenticationConsumptionParams struct {
	CredentialID string             `json:"credential_id"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) InsertAuthenticationConsumption(ctx context.Context, arg InsertAuthenticationConsumptionParams) error {
	_, err := q.db.Exec(ctx, insertAuthenticationConsumption, arg.CredentialID, arg.ExpiresAt)
	return err
}

const lockAuthenticationSettings = `-- name: LockAuthenticationSettings :one
SELECT singleton, password_login_enabled, registration_enabled, registration_email_verification_required, allowed_email_domains, bootstrap_admin_user_id, initialized_at FROM authentication_settings WHERE singleton = TRUE FOR UPDATE
`

func (q *Queries) LockAuthenticationSettings(ctx context.Context) (AuthenticationSetting, error) {
	row := q.db.QueryRow(ctx, lockAuthenticationSettings)
	var i AuthenticationSetting
	err := row.Scan(
		&i.Singleton,
		&i.PasswordLoginEnabled,
		&i.RegistrationEnabled,
		&i.RegistrationEmailVerificationRequired,
		&i.AllowedEmailDomains,
		&i.BootstrapAdminUserID,
		&i.InitializedAt,
	)
	return i, err
}

const lockSecuritySettings = `-- name: LockSecuritySettings :one
SELECT user_id, mode, totp_secret, pending_secret, pending_expires_at, last_totp_step, recovery_hashes, recovery_codes_expires_at, version FROM user_security_settings WHERE user_id=$1 FOR UPDATE
`

func (q *Queries) LockSecuritySettings(ctx context.Context, userID pgtype.UUID) (UserSecuritySetting, error) {
	row := q.db.QueryRow(ctx, lockSecuritySettings, userID)
	var i UserSecuritySetting
	err := row.Scan(
		&i.UserID,
		&i.Mode,
		&i.TotpSecret,
		&i.PendingSecret,
		&i.PendingExpiresAt,
		&i.LastTotpStep,
		&i.RecoveryHashes,
		&i.RecoveryCodesExpiresAt,
		&i.Version,
	)
	return i, err
}

const markEmailVerified = `-- name: MarkEmailVerified :one
UPDATE users SET email_verified_at=NOW() WHERE id=$1 RETURNING id, email, username, password_hash, display_name, is_active, created_at, updated_at, email_verified_at
`

func (q *Queries) MarkEmailVerified(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, markEmailVerified, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmailVerifiedAt,
	)
	return i, err
}

const pruneAuthenticationConsumptions = `-- name: PruneAuthenticationConsumptions :exec
DELETE FROM authentication_consumptions WHERE expires_at < NOW()
`

func (q *Queries) PruneAuthenticationConsumptions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, pruneAuthenticationConsumptions)
	return err
}

const putAuthenticationSettings = `-- name: PutAuthenticationSettings :exec
UPDATE authentication_settings SET password_login_enabled=$1, registration_enabled=$2,
 registration_email_verification_required=$3, allowed_email_domains=$4 WHERE singleton=TRUE
`

type PutAuthenticationSettingsParams struct {
	PasswordLoginEnabled                  bool     `json:"password_login_enabled"`
	RegistrationEnabled                   bool     `json:"registration_enabled"`
	RegistrationEmailVerificationRequired bool     `json:"registration_email_verification_required"`
	AllowedEmailDomains                   []string `json:"allowed_email_domains"`
}

func (q *Queries) PutAuthenticationSettings(ctx context.Context, arg PutAuthenticationSettingsParams) error {
	_, err := q.db.Exec(ctx, putAuthenticationSettings,
		arg.PasswordLoginEnabled,
		arg.RegistrationEnabled,
		arg.RegistrationEmailVerificationRequired,
		arg.AllowedEmailDomains,
	)
	return err
}

const saveConsumedSecurityCredential = `-- name: SaveConsumedSecurityCredential :exec
UPDATE user_security_settings SET last_totp_step=$2,recovery_hashes=$3,version=version+1 WHERE user_id=$1
`

type SaveConsumedSecurityCredentialParams struct {
	UserID         pgtype.UUID `json:"user_id"`
	LastTotpStep   int64       `json:"last_totp_step"`
	RecoveryHashes []string    `json:"recovery_hashes"`
}

func (q *Queries) SaveConsumedSecurityCredential(ctx context.Context, arg SaveConsumedSecurityCredentialParams) error {
	_, err := q.db.Exec(ctx, saveConsumedSecurityCredential, arg.UserID, arg.LastTotpStep, arg.RecoveryHashes)
	return err
}

const saveSecuritySettings = `-- name: SaveSecuritySettings :execrows
UPDATE user_security_settings SET mode=$2,totp_secret=$3,pending_secret=$4,pending_expires_at=$5,
 last_totp_step=$6,recovery_hashes=$7,recovery_codes_expires_at=$9,version=version+1 WHERE user_id=$1 AND version=$8
`

type SaveSecuritySettingsParams struct {
	UserID                 pgtype.UUID        `json:"user_id"`
	Mode                   string             `json:"mode"`
	TotpSecret             []byte             `json:"totp_secret"`
	PendingSecret          []byte             `json:"pending_secret"`
	PendingExpiresAt       pgtype.Timestamptz `json:"pending_expires_at"`
	LastTotpStep           int64              `json:"last_totp_step"`
	RecoveryHashes         []string           `json:"recovery_hashes"`
	Version                int64              `json:"version"`
	RecoveryCodesExpiresAt pgtype.Timestamptz `json:"recovery_codes_expires_at"`
}

func (q *Queries) SaveSecuritySettings(ctx context.Context, arg SaveSecuritySettingsParams) (int64, error) {
	result, err := q.db.Exec(ctx, saveSecuritySettings,
		arg.UserID,
		arg.Mode,
		arg.TotpSecret,
		arg.PendingSecret,
		arg.PendingExpiresAt,
		arg.LastTotpStep,
		arg.RecoveryHashes,
		arg.Version,
		arg.RecoveryCodesExpiresAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
