// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dbgen

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID           pgtype.UUID        `json:"id"`
	RequestID    string             `json:"request_id"`
	ActorID      pgtype.UUID        `json:"actor_id"`
	Action       string             `json:"action"`
	Result       string             `json:"result"`
	ResourceType string             `json:"resource_type"`
	ResourceID   pgtype.Text        `json:"resource_id"`
	IpAddress    *netip.Addr        `json:"ip_address"`
	UserAgent    pgtype.Text        `json:"user_agent"`
	Metadata     []byte             `json:"metadata"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Permission struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Role struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type RolePermission struct {
	RoleID       pgtype.UUID        `json:"role_id"`
	PermissionID pgtype.UUID        `json:"permission_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type TaskDefinition struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	TaskType       string             `json:"task_type"`
	Description    string             `json:"description"`
	DefaultPayload []byte             `json:"default_payload"`
	MaxRetries     int32              `json:"max_retries"`
	TimeoutSeconds int32              `json:"timeout_seconds"`
	IsActive       bool               `json:"is_active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type TaskExecution struct {
	ID             pgtype.UUID        `json:"id"`
	DefinitionID   pgtype.UUID        `json:"definition_id"`
	TaskType       string             `json:"task_type"`
	QueueID        pgtype.Text        `json:"queue_id"`
	IdempotencyKey pgtype.Text        `json:"idempotency_key"`
	Payload        []byte             `json:"payload"`
	Status         string             `json:"status"`
	Attempt        int32              `json:"attempt"`
	ProcessedRows  int64              `json:"processed_rows"`
	ErrorSummary   pgtype.Text        `json:"error_summary"`
	QueuedAt       pgtype.Timestamptz `json:"queued_at"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	FinishedAt     pgtype.Timestamptz `json:"finished_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type TaskOutboxMessage struct {
	QueueID             string             `json:"queue_id"`
	ExecutionID         pgtype.UUID        `json:"execution_id"`
	TaskType            string             `json:"task_type"`
	Payload             []byte             `json:"payload"`
	MaxRetries          int32              `json:"max_retries"`
	TimeoutSeconds      int32              `json:"timeout_seconds"`
	UniqueForSeconds    int32              `json:"unique_for_seconds"`
	ProcessAfterSeconds int32              `json:"process_after_seconds"`
	PublishedAt         pgtype.Timestamptz `json:"published_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type TaskSchedule struct {
	ID             pgtype.UUID        `json:"id"`
	DefinitionID   pgtype.UUID        `json:"definition_id"`
	CronExpression string             `json:"cron_expression"`
	Timezone       string             `json:"timezone"`
	Payload        []byte             `json:"payload"`
	IsEnabled      bool               `json:"is_enabled"`
	LastEnqueuedAt pgtype.Timestamptz `json:"last_enqueued_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	DisplayName  string             `json:"display_name"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type UserRole struct {
	UserID    pgtype.UUID        `json:"user_id"`
	RoleID    pgtype.UUID        `json:"role_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
