// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: preferences.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserPreferences = `-- name: GetUserPreferences :one
SELECT user_id, theme, color_mode, accent_color, font_scale, radius_scale, created_at, updated_at
FROM user_preferences
WHERE user_id = $1
`

func (q *Queries) GetUserPreferences(ctx context.Context, userID pgtype.UUID) (UserPreference, error) {
	row := q.db.QueryRow(ctx, getUserPreferences, userID)
	var i UserPreference
	err := row.Scan(
		&i.UserID,
		&i.Theme,
		&i.ColorMode,
		&i.AccentColor,
		&i.FontScale,
		&i.RadiusScale,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserPreferences = `-- name: UpsertUserPreferences :exec
INSERT INTO user_preferences (user_id, theme, color_mode, accent_color, font_scale, radius_scale)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (user_id) DO UPDATE
SET theme = EXCLUDED.theme,
    color_mode = EXCLUDED.color_mode,
    accent_color = EXCLUDED.accent_color,
    font_scale = EXCLUDED.font_scale,
    radius_scale = EXCLUDED.radius_scale,
    updated_at = NOW()
`

type UpsertUserPreferencesParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	Theme       string      `json:"theme"`
	ColorMode   string      `json:"color_mode"`
	AccentColor pgtype.Text `json:"accent_color"`
	FontScale   string      `json:"font_scale"`
	RadiusScale string      `json:"radius_scale"`
}

func (q *Queries) UpsertUserPreferences(ctx context.Context, arg UpsertUserPreferencesParams) error {
	_, err := q.db.Exec(ctx, upsertUserPreferences,
		arg.UserID,
		arg.Theme,
		arg.ColorMode,
		arg.AccentColor,
		arg.FontScale,
		arg.RadiusScale,
	)
	return err
}
