// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AssignUserRole(ctx context.Context, arg AssignUserRoleParams) error
	CountFilteredAuditLogs(ctx context.Context, arg CountFilteredAuditLogsParams) (int64, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error)
	CreateTaskDefinition(ctx context.Context, arg CreateTaskDefinitionParams) (TaskDefinition, error)
	CreateTaskExecution(ctx context.Context, arg CreateTaskExecutionParams) (TaskExecution, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	GetPermissionByName(ctx context.Context, name string) (Permission, error)
	GetRoleByName(ctx context.Context, name string) (Role, error)
	GetTaskExecution(ctx context.Context, id pgtype.UUID) (TaskExecution, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GrantRolePermission(ctx context.Context, arg GrantRolePermissionParams) error
	ListEnabledTaskSchedules(ctx context.Context) ([]TaskSchedule, error)
	ListFilteredAuditLogs(ctx context.Context, arg ListFilteredAuditLogsParams) ([]AuditLog, error)
	ListPermissions(ctx context.Context) ([]Permission, error)
	ListRoles(ctx context.Context) ([]Role, error)
	ListUserPermissions(ctx context.Context, userID pgtype.UUID) ([]string, error)
	SetUserActive(ctx context.Context, arg SetUserActiveParams) error
	UpdateTaskExecutionStatus(ctx context.Context, arg UpdateTaskExecutionStatusParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error
}

var _ Querier = (*Queries)(nil)
