// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: tasks.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTaskDefinition = `-- name: CreateTaskDefinition :one
INSERT INTO task_definitions (
    name, task_type, description, default_payload, max_retries, timeout_seconds
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, task_type, description, default_payload, max_retries, timeout_seconds, is_active, created_at, updated_at
`

type CreateTaskDefinitionParams struct {
	Name           string `json:"name"`
	TaskType       string `json:"task_type"`
	Description    string `json:"description"`
	DefaultPayload []byte `json:"default_payload"`
	MaxRetries     int32  `json:"max_retries"`
	TimeoutSeconds int32  `json:"timeout_seconds"`
}

func (q *Queries) CreateTaskDefinition(ctx context.Context, arg CreateTaskDefinitionParams) (TaskDefinition, error) {
	row := q.db.QueryRow(ctx, createTaskDefinition,
		arg.Name,
		arg.TaskType,
		arg.Description,
		arg.DefaultPayload,
		arg.MaxRetries,
		arg.TimeoutSeconds,
	)
	var i TaskDefinition
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TaskType,
		&i.Description,
		&i.DefaultPayload,
		&i.MaxRetries,
		&i.TimeoutSeconds,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTaskExecution = `-- name: CreateTaskExecution :one
INSERT INTO task_executions (definition_id, task_type, queue_id, idempotency_key, payload)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, definition_id, task_type, queue_id, idempotency_key, payload, status, attempt, processed_rows, error_summary, queued_at, started_at, finished_at, created_at, updated_at
`

type CreateTaskExecutionParams struct {
	DefinitionID   pgtype.UUID `json:"definition_id"`
	TaskType       string      `json:"task_type"`
	QueueID        pgtype.Text `json:"queue_id"`
	IdempotencyKey pgtype.Text `json:"idempotency_key"`
	Payload        []byte      `json:"payload"`
}

func (q *Queries) CreateTaskExecution(ctx context.Context, arg CreateTaskExecutionParams) (TaskExecution, error) {
	row := q.db.QueryRow(ctx, createTaskExecution,
		arg.DefinitionID,
		arg.TaskType,
		arg.QueueID,
		arg.IdempotencyKey,
		arg.Payload,
	)
	var i TaskExecution
	err := row.Scan(
		&i.ID,
		&i.DefinitionID,
		&i.TaskType,
		&i.QueueID,
		&i.IdempotencyKey,
		&i.Payload,
		&i.Status,
		&i.Attempt,
		&i.ProcessedRows,
		&i.ErrorSummary,
		&i.QueuedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskExecution = `-- name: GetTaskExecution :one
SELECT id, definition_id, task_type, queue_id, idempotency_key, payload, status, attempt, processed_rows, error_summary, queued_at, started_at, finished_at, created_at, updated_at FROM task_executions WHERE id = $1
`

func (q *Queries) GetTaskExecution(ctx context.Context, id pgtype.UUID) (TaskExecution, error) {
	row := q.db.QueryRow(ctx, getTaskExecution, id)
	var i TaskExecution
	err := row.Scan(
		&i.ID,
		&i.DefinitionID,
		&i.TaskType,
		&i.QueueID,
		&i.IdempotencyKey,
		&i.Payload,
		&i.Status,
		&i.Attempt,
		&i.ProcessedRows,
		&i.ErrorSummary,
		&i.QueuedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledTaskSchedules = `-- name: ListEnabledTaskSchedules :many
SELECT id, definition_id, cron_expression, timezone, payload, is_enabled, last_enqueued_at, created_at, updated_at FROM task_schedules WHERE is_enabled = TRUE ORDER BY created_at, id
`

func (q *Queries) ListEnabledTaskSchedules(ctx context.Context) ([]TaskSchedule, error) {
	rows, err := q.db.Query(ctx, listEnabledTaskSchedules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskSchedule{}
	for rows.Next() {
		var i TaskSchedule
		if err := rows.Scan(
			&i.ID,
			&i.DefinitionID,
			&i.CronExpression,
			&i.Timezone,
			&i.Payload,
			&i.IsEnabled,
			&i.LastEnqueuedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTaskExecutionStatus = `-- name: UpdateTaskExecutionStatus :exec
UPDATE task_executions
SET status = $2, started_at = $3, finished_at = $4, error_summary = $5,
    processed_rows = $6, attempt = $7, updated_at = NOW()
WHERE id = $1
`

type UpdateTaskExecutionStatusParams struct {
	ID            pgtype.UUID        `json:"id"`
	Status        string             `json:"status"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	FinishedAt    pgtype.Timestamptz `json:"finished_at"`
	ErrorSummary  pgtype.Text        `json:"error_summary"`
	ProcessedRows int64              `json:"processed_rows"`
	Attempt       int32              `json:"attempt"`
}

func (q *Queries) UpdateTaskExecutionStatus(ctx context.Context, arg UpdateTaskExecutionStatusParams) error {
	_, err := q.db.Exec(ctx, updateTaskExecutionStatus,
		arg.ID,
		arg.Status,
		arg.StartedAt,
		arg.FinishedAt,
		arg.ErrorSummary,
		arg.ProcessedRows,
		arg.Attempt,
	)
	return err
}
