"use client";

import * as AlertDialogPrimitive from "@radix-ui/react-alert-dialog";
import * as CheckboxPrimitive from "@radix-ui/react-checkbox";
import * as DialogPrimitive from "@radix-ui/react-dialog";
import * as LabelPrimitive from "@radix-ui/react-label";
import * as SelectPrimitive from "@radix-ui/react-select";
import * as TabsPrimitive from "@radix-ui/react-tabs";
import { Check, ChevronDown, ChevronLeft, ChevronRight, ChevronUp, ChevronsLeft, ChevronsRight, MoreHorizontal, X } from "lucide-react";
import * as React from "react";
import { cn } from "../shared/cn";
import { Button, buttonVariants, type ButtonProps } from "./button";

export function Checkbox({ className, ...props }: React.ComponentProps<typeof CheckboxPrimitive.Root>) { return <CheckboxPrimitive.Root className={cn("flex size-4 shrink-0 items-center justify-center border border-[color:var(--input)] bg-[color:var(--input-background)] text-[color:var(--primary-foreground)] [border-radius:var(--radius-sm)] data-[state=checked]:border-[color:var(--primary)] data-[state=checked]:bg-[color:var(--primary)] focus-visible:ring-2 focus-visible:ring-[color:var(--ring)] disabled:opacity-50", className)} {...props}><CheckboxPrimitive.Indicator><Check className="size-3.5" /></CheckboxPrimitive.Indicator></CheckboxPrimitive.Root>; }
export function Label({ className, ...props }: React.ComponentProps<typeof LabelPrimitive.Root>) { return <LabelPrimitive.Root className={cn("flex items-center gap-2 text-[length:var(--text-label)] font-medium", className)} {...props} />; }

export const Dialog = DialogPrimitive.Root;
export const DialogTrigger = DialogPrimitive.Trigger;
export const DialogClose = DialogPrimitive.Close;
export function DialogOverlay({ className, ...props }: React.ComponentProps<typeof DialogPrimitive.Overlay>) { return <DialogPrimitive.Overlay className={cn("fixed inset-0 z-50 bg-[color:var(--overlay)]", className)} {...props} />; }
export type DialogContentProps = React.ComponentProps<typeof DialogPrimitive.Content> & { showClose?: boolean; closeLabel?: string };
export function DialogContent({ className, children, showClose = true, closeLabel = "Close", ...props }: DialogContentProps) { return <DialogPrimitive.Portal><DialogOverlay /><DialogPrimitive.Content className={cn("fixed left-1/2 top-1/2 z-[60] flex max-h-[min(44rem,calc(100vh-2rem))] w-[min(36rem,calc(100vw-2rem))] -translate-x-1/2 -translate-y-1/2 flex-col border border-[color:var(--border)] bg-[color:var(--popover)] text-[color:var(--popover-foreground)] shadow-[var(--shadow-dialog)] outline-none [border-radius:var(--radius-xl)]", className)} {...props}>{children}{showClose ? <DialogPrimitive.Close className="absolute right-4 top-4 inline-flex size-8 items-center justify-center [border-radius:var(--radius-md)] hover:bg-[color:var(--accent)]"><X className="size-4" /><span className="sr-only">{closeLabel}</span></DialogPrimitive.Close> : null}</DialogPrimitive.Content></DialogPrimitive.Portal>; }
export function DialogHeader({ className, ...props }: React.HTMLAttributes<HTMLDivElement>) { return <div className={cn("flex flex-col gap-1 border-b border-[color:var(--border)] px-5 py-4 pr-12", className)} {...props} />; }
export function DialogFooter({ className, ...props }: React.HTMLAttributes<HTMLDivElement>) { return <div className={cn("flex flex-wrap justify-end gap-2 border-t border-[color:var(--border)] px-5 py-4", className)} {...props} />; }
export function DialogTitle({ className, ...props }: React.ComponentProps<typeof DialogPrimitive.Title>) { return <DialogPrimitive.Title className={cn("text-[length:var(--text-heading)] font-semibold", className)} {...props} />; }
export function DialogDescription({ className, ...props }: React.ComponentProps<typeof DialogPrimitive.Description>) { return <DialogPrimitive.Description className={cn("text-[length:var(--text-body-sm)] text-[color:var(--muted-foreground)]", className)} {...props} />; }

export const AlertDialog = AlertDialogPrimitive.Root;
export const AlertDialogTrigger = AlertDialogPrimitive.Trigger;
export function AlertDialogContent({ className, children, ...props }: React.ComponentProps<typeof AlertDialogPrimitive.Content>) { return <AlertDialogPrimitive.Portal><AlertDialogPrimitive.Overlay className="fixed inset-0 z-50 bg-[color:var(--overlay)]" /><AlertDialogPrimitive.Content className={cn("fixed left-1/2 top-1/2 z-[60] w-[min(30rem,calc(100vw-2rem))] -translate-x-1/2 -translate-y-1/2 border border-[color:var(--border)] bg-[color:var(--popover)] p-5 text-[color:var(--popover-foreground)] shadow-[var(--shadow-dialog)] [border-radius:var(--radius-xl)]", className)} {...props}>{children}</AlertDialogPrimitive.Content></AlertDialogPrimitive.Portal>; }
export function AlertDialogHeader({ className, ...props }: React.HTMLAttributes<HTMLDivElement>) { return <div className={cn("grid gap-1.5", className)} {...props} />; }
export function AlertDialogFooter({ className, ...props }: React.HTMLAttributes<HTMLDivElement>) { return <div className={cn("mt-6 flex flex-wrap justify-end gap-2", className)} {...props} />; }
export function AlertDialogTitle({ className, ...props }: React.ComponentProps<typeof AlertDialogPrimitive.Title>) { return <AlertDialogPrimitive.Title className={cn("text-[length:var(--text-heading)] font-semibold", className)} {...props} />; }
export function AlertDialogDescription({ className, ...props }: React.ComponentProps<typeof AlertDialogPrimitive.Description>) { return <AlertDialogPrimitive.Description className={cn("text-[length:var(--text-body-sm)] text-[color:var(--muted-foreground)]", className)} {...props} />; }
export function AlertDialogAction({ className, variant = "destructive", ...props }: React.ComponentProps<typeof AlertDialogPrimitive.Action> & { variant?: NonNullable<ButtonProps["variant"]> }) { return <AlertDialogPrimitive.Action className={cn(buttonVariants({ variant }), className)} {...props} />; }
export function AlertDialogCancel({ className, ...props }: React.ComponentProps<typeof AlertDialogPrimitive.Cancel>) { return <AlertDialogPrimitive.Cancel className={cn(buttonVariants({ variant: "outline" }), className)} {...props} />; }

export const Select = SelectPrimitive.Root;
export const SelectGroup = SelectPrimitive.Group;
export const SelectValue = SelectPrimitive.Value;
export function SelectTrigger({ className, children, ...props }: React.ComponentProps<typeof SelectPrimitive.Trigger>) { return <SelectPrimitive.Trigger className={cn("flex h-10 w-full items-center justify-between gap-2 border border-[color:var(--input)] bg-[color:var(--input-background)] px-3 text-left text-[length:var(--text-body-sm)] text-[color:var(--foreground)] outline-none [border-radius:var(--radius-md)] data-[placeholder]:text-[color:var(--muted-foreground)] focus-visible:border-[color:var(--ring)] focus-visible:ring-2 focus-visible:ring-[color:var(--ring)] disabled:cursor-not-allowed disabled:opacity-50", className)} {...props}>{children}<SelectPrimitive.Icon asChild><ChevronDown aria-hidden="true" className="size-4 shrink-0 text-[color:var(--muted-foreground)]" /></SelectPrimitive.Icon></SelectPrimitive.Trigger>; }
export function SelectContent({ className, children, position = "popper", ...props }: React.ComponentProps<typeof SelectPrimitive.Content>) { return <SelectPrimitive.Portal><SelectPrimitive.Content position={position} className={cn("z-[80] max-h-72 overflow-hidden border border-[color:var(--border)] bg-[color:var(--popover)] text-[color:var(--popover-foreground)] shadow-[var(--shadow-popover)] [border-radius:var(--radius-lg)]", className)} {...props}><SelectScrollUpButton /><SelectPrimitive.Viewport className={cn("p-1", position === "popper" && "w-[var(--radix-select-trigger-width)] min-w-[var(--radix-select-trigger-width)]")}>{children}</SelectPrimitive.Viewport><SelectScrollDownButton /></SelectPrimitive.Content></SelectPrimitive.Portal>; }
export function SelectLabel({ className, ...props }: React.ComponentProps<typeof SelectPrimitive.Label>) { return <SelectPrimitive.Label className={cn("px-2 py-1.5 text-[length:var(--text-caption)] font-medium text-[color:var(--muted-foreground)]", className)} {...props} />; }
export function SelectItem({ className, children, ...props }: React.ComponentProps<typeof SelectPrimitive.Item>) { return <SelectPrimitive.Item className={cn("relative flex min-h-9 w-full cursor-default select-none items-center gap-2 py-1.5 pl-2 pr-8 text-[length:var(--text-body-sm)] text-[color:var(--popover-foreground)] outline-none [border-radius:var(--radius-sm)] data-[highlighted]:bg-[color:var(--accent)] data-[highlighted]:text-[color:var(--accent-foreground)] data-[state=checked]:bg-[color:var(--primary-subtle)] data-[state=checked]:text-[color:var(--primary-subtle-foreground)] data-[disabled]:pointer-events-none data-[disabled]:opacity-50", className)} {...props}><span className="absolute right-2 flex size-4 items-center justify-center"><SelectPrimitive.ItemIndicator><Check aria-hidden="true" className="size-3.5" /></SelectPrimitive.ItemIndicator></span><SelectPrimitive.ItemText>{children}</SelectPrimitive.ItemText></SelectPrimitive.Item>; }
export function SelectSeparator({ className, ...props }: React.ComponentProps<typeof SelectPrimitive.Separator>) { return <SelectPrimitive.Separator className={cn("-mx-1 my-1 h-px bg-[color:var(--border)]", className)} {...props} />; }
export function SelectScrollUpButton({ className, ...props }: React.ComponentProps<typeof SelectPrimitive.ScrollUpButton>) { return <SelectPrimitive.ScrollUpButton className={cn("flex h-7 cursor-default items-center justify-center", className)} {...props}><ChevronUp aria-hidden="true" className="size-4" /></SelectPrimitive.ScrollUpButton>; }
export function SelectScrollDownButton({ className, ...props }: React.ComponentProps<typeof SelectPrimitive.ScrollDownButton>) { return <SelectPrimitive.ScrollDownButton className={cn("flex h-7 cursor-default items-center justify-center", className)} {...props}><ChevronDown aria-hidden="true" className="size-4" /></SelectPrimitive.ScrollDownButton>; }

export function Tabs({ className, ...props }: React.ComponentProps<typeof TabsPrimitive.Root>) { return <TabsPrimitive.Root className={cn("flex flex-col gap-5", className)} {...props} />; }
export function TabsList({ className, ...props }: React.ComponentProps<typeof TabsPrimitive.List>) { return <TabsPrimitive.List className={cn("inline-flex min-h-10 w-fit flex-wrap items-center gap-1 border border-[color:var(--border)] bg-[color:var(--muted)] p-1 [border-radius:var(--radius-lg)]", className)} {...props} />; }
export function TabsTrigger({ className, ...props }: React.ComponentProps<typeof TabsPrimitive.Trigger>) { return <TabsPrimitive.Trigger className={cn("inline-flex h-8 items-center px-3 text-[length:var(--text-label)] font-medium [border-radius:var(--radius-md)] data-[state=active]:bg-[color:var(--card)] data-[state=active]:text-[color:var(--foreground)]", className)} {...props} />; }
export function TabsContent({ className, ...props }: React.ComponentProps<typeof TabsPrimitive.Content>) { return <TabsPrimitive.Content className={cn("outline-none", className)} {...props} />; }

export function Pagination({ className, "aria-label": ariaLabel = "Pagination", ...props }: React.ComponentProps<"nav">) { return <nav aria-label={ariaLabel} className={cn("mx-auto flex w-full justify-center", className)} {...props} />; }
export function PaginationContent({ className, ...props }: React.ComponentProps<"ul">) { return <ul className={cn("flex flex-wrap items-center justify-center gap-1", className)} {...props} />; }
export function PaginationItem(props: React.ComponentProps<"li">) { return <li {...props} />; }
export function PaginationLink({ className, isActive, ...props }: React.ComponentProps<"button"> & { isActive?: boolean }) { return <button type="button" aria-current={isActive ? "page" : undefined} className={cn(buttonVariants({ variant: isActive ? "default" : "outline", size: "icon" }), className)} {...props} />; }
export function PaginationFirst({ children = "First", ...props }: React.ComponentProps<typeof Button>) { return <Button type="button" variant="outline" {...props}><ChevronsLeft aria-hidden="true" className="size-4" />{children}</Button>; }
export function PaginationPrevious({ children = "Previous", ...props }: React.ComponentProps<typeof Button>) { return <Button type="button" variant="outline" {...props}><ChevronLeft aria-hidden="true" className="size-4" />{children}</Button>; }
export function PaginationNext({ children = "Next", ...props }: React.ComponentProps<typeof Button>) { return <Button type="button" variant="outline" {...props}>{children}<ChevronRight aria-hidden="true" className="size-4" /></Button>; }
export function PaginationLast({ children = "Last", ...props }: React.ComponentProps<typeof Button>) { return <Button type="button" variant="outline" {...props}>{children}<ChevronsRight aria-hidden="true" className="size-4" /></Button>; }
export interface PaginationEllipsisProps extends React.ComponentProps<"span"> { label?: string; }
export function PaginationEllipsis({ label = "More pages", ...props }: PaginationEllipsisProps) { return <span className="flex size-9 items-center justify-center" {...props}><MoreHorizontal aria-hidden="true" className="size-4" /><span className="sr-only">{label}</span></span>; }
